version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/PY_PIPE   # Replace with your actual app directory

permissions:
  - object: /home/ec2-user/PY_PIPE
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
    - command: chmod +x scripts/install_dependencies.sh   # Ensure script has executable permissions

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/cleanup.sh
      timeout: 300
      runas: ec2-user
