version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/myapp   # Replace with your app directory

permissions:
  - object: /home/ubuntu/myapp
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - command: chmod +x scripts/install_dependencies.sh   # Ensure script has executable permissions

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
