version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
      docker: 18
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Build started"
      - python -m unittest discover -s tests/ -p '*_test.py'

artifacts:
  files:
    - '**/*'
  discard-paths: yes
